export const rowData = [
  {
    id: "fb4783c5-aefc-55cd-9932-fe6a2aca4177",
    date: "11 October 2023",
    listing_title: "Private Apartment in Lagos",
    status: "Pending",
    amount: "$200",
    beds: 4,
    rooms: 5,
    bathrooms: 4,
    guests: 4,
  },
  {
    id: "fb4783c5-aefc-55cd-9932-fe6a2aca4177",
    date: "11 October 2023",
    listing_title: "Private Apartment in Lagos",
    status: "Pending",
    amount: "$200",
    beds: 4,
    rooms: 5,
    bathrooms: 4,
    guests: 4,
  },
  {
    id: "fb4783c5-aefc-55cd-9932-fe6a2aca4177",
    date: "11 October 2023",
    listing_title: "Private Apartment in Lagos",
    status: "Pending",
    amount: "$200",
    beds: 4,
    rooms: 5,
    bathrooms: 4,
    guests: 4,
  },
  {
    id: "fb4783c5-aefc-55cd-9932-fe6a2aca4177",
    date: "11 October 2023",
    listing_title: "Private Apartment in Lagos",
    status: "Pending",
    amount: "$200",
    beds: 4,
    rooms: 5,
    bathrooms: 4,
    guests: 4,
  },
];

export const columnsData = [
  { field: "date", headerName: "DATE", width: 170 },
  { field: "listing_title", headerName: "LISITNG", width: 350 },
  { field: "status", headerName: "STATUS", width: 120 },
  { field: "amount", headerName: "Amount", width: 130 },
  { field: "beds", headerName: "Beds", width: 100 },
  { field: "rooms", headerName: "Rooms", width: 100 },
  { field: "bathrooms", headerName: "Bathrooms", width: 100 },
  { field: "guests", headerName: "Guests", width: 100 },
];
